### ISSUE TITLE
It seems that access to /storage/emulated/0 is not possible.

### ISSUE THREAD

**Issue by Aloereed** [snickler/WSA-Patched#1]
![image](https://github.com/user-attachments/assets/94ca0a84-054a-45ee-8bf4-adc15af62bb2)
First of all, thank you for the significant contributions you have made to the X Elite device. Regarding this issue, it means that the software cannot access external storage, which prevents many applications from functioning properly.

**Comment by snickler** [comment]
Thanks for this @Aloereed . Someone else reported this to me during some early testing. I'm going to take a look at this and see why that is happening. I'll take a look at why this is happening. It's most likely permissions not being set properly once I recreated the vhdx.

**Comment by snickler** [comment]
Yeah that's exactly what happened. 

![image](https://github.com/user-attachments/assets/dda47a4b-eebb-4ae7-8ad5-656a024cd0e3)

**Comment by snickler** [comment]
Fixed 

https://github.com/snickler/WSA-Patched/releases/tag/0.0.2
