### ISSUE TITLE
WSA has updated to 2407.40000. Dose 2311.40000 still work?

### ISSUE THREAD

**Issue by Ryanwu316** [snickler/WSA-Patched#2]

**Comment by snickler** [comment]
Good call out. I'll test with 2407.40000 and put up new images. I'm working on a script to do all the modifications, but in the meantime we'll see how far we get.

**Comment by Ryanwu316** [comment]
I tried, it works on my surface pro 11.

**Comment by tristan-k** [comment]
On my surface pro 11 there was `WindowsSubsystemForAndroid_2302.40000.9.0_arm64` pre-installed. I followed the instructions at [xda-developers](https://www.xda-developers.com/windows-subsystem-for-android-snapdragon-how-to/) but I'm unable to start the android system settings or any other android app.

**Comment by snickler** [comment]
You need to update to something at least 2311.40000, per the original instructions.

Jeremy Sinclair
Windows Development MVP
Avalonia MVP

[signatureImage]

[signatureImage]
________________________________

**Comment by tristan-k** [comment]
Thanks. I got it working. I had to uninstall the old version and reinstall the [Amazon App Store](https://apps.microsoft.com/detail/9njhk44ttksx?hl=en-us&gl=US) from the Microsoft Store.

**Comment by tristan-k** [comment]
Off-topic but is anyone able to playback media? As soon as I start somekind of media (eg audio or video) the app (eg AntennaPod) freezes or crashes.

**Comment by snickler** [comment]
> Off-topic but is anyone able to playback media? As soon as I start somekind of media (eg audio or video) the app (eg AntennaPod) freezes or crashes.

I'm working on fixing that one. I have audio working, but I still haven't gotten video to work. I'm going to post up a new set of VHDXs today that'll make audio work.

**Comment by snickler** [comment]
https://github.com/snickler/WSA-Patched/releases/tag/0.0.2
