### ISSUE TITLE
insufficient permissions to move VHDX files

### ISSUE THREAD

**Issue by ghost** [snickler/WSA-Patched#4]

**Comment by snickler** [comment]
@Larryhan878  - Are you moving the VHDX files to the custom WSA install directory you created? If so, make sure that WSA is shut down completely. If the `Windows Subsystem for Android` service is still running while you try to copy these, it will fail.

**Comment by Larryhan878** [comment]
@snickler Hello, I think it was a mistake in my own steps that caused the problem. What does "go through the steps the XDA Developers and Windows Central posts tell you to do" mean? I can't understand him.

**Comment by Larryhan878** [comment]
@snickler I am very sorry, as I do not speak English, I am using a translation tool, but the translated content is very strange and makes it difficult for me to understand. Thank you for your help.
